In [1]:
import numpy as np
x = np.array([1, 3, 4, 7, 9, 12, 13, 14])
y = np.array([3.5, 2.4, 2.1, 1.3, 1.2, 2.2, 2.6, 4.2])
print(x)
print(y)
print(len(x), len(y))

[ 1  3  4  7  9 12 13 14]
[3.5 2.4 2.1 1.3 1.2 2.2 2.6 4.2]
8 8


In [2]:
var_x = np.array([i - np.mean(x) for i in x])
var_y = np.array([i - np.mean(y) for i in y])
print(var_x)
print(var_y)

[-6.875 -4.875 -3.875 -0.875  1.125  4.125  5.125  6.125]
[ 1.0625 -0.0375 -0.3375 -1.1375 -1.2375 -0.2375  0.1625  1.7625]


In [6]:
S_xx = 0
for i in var_x:
    S_xx += i**2

S_yy = 0
for i in var_y:
    S_yy += i**2
    

S_xy = 0
for i in range(0, len(var_x)):
    S_xy += var_x[i] * var_y[i]
    
print(S_xx)
print(S_yy)
print(S_xy)

168.875
7.258750000000001
4.437500000000003


In [9]:
import math

r = S_xy / (math.sqrt(S_xx) * math.sqrt(S_yy))
print(r)

0.12674322847596553
